# Generated by Django 4.2.16 on 2026-07-31 21:20

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('author', models.CharField(db_index=True, max_length=255)),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('isbn_normalized', models.CharField(editable=False, max_length=13, unique=True)),
                ('cost_usd', models.DecimalField(decimal_places=2, help_text='Purchase cost in US dollars. Must be greater than 0.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('selling_price_local', models.DecimalField(blank=True, decimal_places=2, help_text='Filled in by POST /books/{id}/calculate-price.', max_digits=14, null=True)),
                ('selling_price_currency', models.CharField(blank=True, default='', max_length=3)),
                ('price_calculated_at', models.DateTimeField(blank=True, null=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('category', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('supplier_country', models.CharField(blank=True, default='', help_text='ISO 3166-1 alpha-2 code, e.g. ES.', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'book',
                'verbose_name_plural': 'books',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['category', 'stock_quantity'], name='books_book_categor_545add_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.CheckConstraint(check=models.Q(('cost_usd__gt', Decimal('0'))), name='book_cost_usd_positive'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.CheckConstraint(check=models.Q(('stock_quantity__gte', 0)), name='book_stock_not_negative'),
        ),
    ]
